add ids for tooltips
harness/ng-tooltip pull request #261
Opened 2023-01-05 07:38 UTC by SmritiSatya

Signed-off-by: Smriti S <smriti.satyanarayana@harness.io>

2023-01-06 12:45 UTC, deepakbolangady requested changes
Thanks for sending these tooltips for a review, Smriti. Please reach out if you have any questions about my feedback or you want to discuss specific comments. I'll be glad to explain my comments in more detail. - Deepak

2023-01-06 12:45 UTC, deepakbolangady commented on src/Tooltip/TooltipDictionary.yaml
> +    content: Specify size of the files utilized (in GB)
"the size"
I would also look at the word "utilized" closely. Are the files being utilized (vs. used)? If it is accurate, please ignore this comment. Thanks.

2023-01-06 12:45 UTC, deepakbolangady commented on src/Tooltip/TooltipDictionary.yaml
> +    content: Latency/delay (in milliseconds)
Needs a little more? Ignore if you feel it's sufficient. If the field name is "Network Latency" and the tooltip says "Latency," I would say we don't need a tooltip at all. If we choose to have a tooltip, we should be more descriptive.

2023-01-06 12:45 UTC, deepakbolangady commented on src/Tooltip/TooltipDictionary.yaml
> +    content: Packet corruption in percent
Use parentheses for consistency with other similar descriptions.

2023-01-06 12:45 UTC, deepakbolangady commented on src/Tooltip/TooltipDictionary.yaml
> +    content: IP addresses of the services/pods/CIDR blocks(range of IPs) whose accessibility is affected
IPs -> always spell out as "IP addresses." Also, since we cannot have "IP addresses of CIDR blocks," we should rewrite. Is the following text technically accurate? 
IP addresses of the services or pods whose accessibility you want to affect. You can also specify a CIDR block.

2023-01-06 12:45 UTC, deepakbolangady commented on src/Tooltip/TooltipDictionary.yaml
> +    content: Image for traffic control in Linux
What does "in Linux" signify? Do we mean "Image for controlling traffic associated with a Linux machine?" Or do we mean "Linux image for controlling traffic." (If it is the latter, we will need more information. Thanks.)

2023-01-06 12:45 UTC, deepakbolangady commented on src/Tooltip/TooltipDictionary.yaml
> +    content: Image to run the netem command OR Image used to kill the container
Are we undecided on the description? (referring to the OR).

2023-01-06 13:10 UTC, SmritiSatya commented on src/Tooltip/TooltipDictionary.yaml
> +    content: Image to run the netem command OR Image used to kill the container
Yes, I saw two descriptions for the same tooltip.

2023-01-07 04:43 UTC, SmritiSatya commented on src/Tooltip/TooltipDictionary.yaml
> +    content: Introduces randomness in pod deletions with a minimum period defined by CHAOS_INTERVAL
CHAOS_INTERNVAL is an environment variable, so I am not sure I can change the case.

2023-01-07 04:45 UTC, SmritiSatya commented on src/Tooltip/TooltipDictionary.yaml
> +    content: Percentage of total pods the chaos targets
It would be "Percentage of total pods that the chaos targets"

2023-01-07 04:47 UTC, SmritiSatya commented on src/Tooltip/TooltipDictionary.yaml
> +    content: Chaos library used to inject chaos
Sure! User has to enter information into these fields, so I will specify that.

2023-01-09 16:32 UTC, SmritiSatya commented on src/Tooltip/TooltipDictionary.yaml
> +    content: HTTP response body that is overwritten by the body of the string
Changed 'string' to 'response string'.

2023-01-21 07:31 UTC, SahilKr24 requested changes

2023-01-21 07:31 UTC, SahilKr24 commented on src/Tooltip/TooltipDictionary.yaml
> +tune_fault_total_chaos_duration:
```suggestion
chaos_tune_fault_total_chaos_duration:
```

same for all `tune_fault_{tunables}`

2023-01-21 07:36 UTC, SahilKr24 commented
Found these tooltips missing while verifying with the code. PTAL.
```
chaos_target_app_ns
chaos_target_app_kind
chaos_target_app_label
```

```
chaos_infra_cluster_scope
chaos_infra_namespace_scope
```

Assuming these mentioned below two were removed on purpose.
```
chaos_probe_prom_type
chaos_probe_cmd_source 
```

2023-01-22 12:13 UTC, SahilKr24 approved these changes
Verified all tooltip keys against frontend code. Good to go.
🚀

2023-01-24 07:43 UTC, neelanjan00 requested changes

2023-01-24 07:43 UTC, neelanjan00 commented on src/Tooltip/TooltipDictionary.yaml
> +    content: Number of I/O workers involved in I/O disk stress.
```suggestion
    content: Number of IO workers involved in disk IO stress.
```

2023-01-24 07:43 UTC, neelanjan00 commented on src/Tooltip/TooltipDictionary.yaml
> +    content: Specify the size of the files used (in GB).
```suggestion
    content: Specify the size of the files used per worker (in GB).
```

2023-01-24 07:43 UTC, neelanjan00 commented on src/Tooltip/TooltipDictionary.yaml
> +    content: Memory required to fill the volume mount path provided.
```suggestion
    content: Mount path to be used for the IO stress.
```

2023-01-24 07:43 UTC, neelanjan00 commented on src/Tooltip/TooltipDictionary.yaml
> +    width: "400"
Let's keep this ENV description generic as it is being used in other faults too.

2023-01-24 07:43 UTC, neelanjan00 commented on src/Tooltip/TooltipDictionary.yaml
> +    content: Name of the probe used to perform chaos experiment health check.
```suggestion
    content: Name of the probe for the given fault. 
```

2023-01-24 07:43 UTC, neelanjan00 commented on src/Tooltip/TooltipDictionary.yaml
> +    content:  Initial waiting time interval for the probe (in seconds).
```suggestion
    content: Initial waiting time interval for the probe (in seconds).
```

2023-01-24 07:43 UTC, neelanjan00 commented on src/Tooltip/TooltipDictionary.yaml
> +    content: If the URL specified is secure (that is, HTTPS), check the skip certificate checks checkbox, else uncheck it.
```suggestion
    content: If the URL specified is secure (i.e. HTTPS), check the skip certificate checks checkbox in case you don't want to perform the certificate check during the probe execution, else uncheck it.
```

2023-01-24 07:43 UTC, neelanjan00 commented on src/Tooltip/TooltipDictionary.yaml
> +    content: Encoding used for the body (for HTTP POST request only).
```suggestion
    content: The Content-Type representation header used for the body (for HTTP POST request only).
```

2023-01-24 07:43 UTC, neelanjan00 commented on src/Tooltip/TooltipDictionary.yaml
> +    content: Content present inside the HTTP POST request.
```suggestion
    content: Content to be put inside the HTTP POST request body.
```

2023-01-24 07:43 UTC, neelanjan00 commented on src/Tooltip/TooltipDictionary.yaml
> +    content: The value that is mapped against the received status code to validate the probe. If the value is 200, it indicates successful validation of the probe.
```suggestion
    content: The value that is mapped against the received status code to validate the probe.
```

200 response code may not be the expected validation criteria at times. Better not to specify this.

2023-01-24 07:43 UTC, neelanjan00 commented on src/Tooltip/TooltipDictionary.yaml
> +    content: Command that you need to execute in the command probe.
```suggestion
    content: Command to execute in the command probe.
```

2023-01-24 07:43 UTC, neelanjan00 commented on src/Tooltip/TooltipDictionary.yaml
> +    content: Specify the namespace where your target application will be housed.
```suggestion
    content: Specify the namespace where your target application is present.
```

2023-01-24 07:43 UTC, neelanjan00 commented on src/Tooltip/TooltipDictionary.yaml
> +    content: Annotation specified by the user with respect to the tagret application. For example, nginx target application can have the label as app=nginx.
```suggestion
    content: Label of the target application. For example, nginx target application can have the label app=nginx. 
```

2023-01-24 07:43 UTC, neelanjan00 commented on src/Tooltip/TooltipDictionary.yaml
> +    content: This scope indicates that the chaos infrastructure will be accessible in all namespaces in the cluster.
```suggestion
    content: This scope indicates that the chaos infrastructure will be able to access and target chaos in all namespaces of the cluster.
```

2023-01-24 07:43 UTC, neelanjan00 commented on src/Tooltip/TooltipDictionary.yaml
> +    content: This scope indicates that the chaos infrastructure will be accessible in a specific namespace only.
```suggestion
    content: This scope indicates that the chaos infrastructure will be able to access and target chaos in one specific namespace only.
```

2023-01-24 07:43 UTC, neelanjan00 commented on src/Tooltip/TooltipDictionary.yaml
> +    content: Displays the number of probes that passed and failed the checks.
```suggestion
    content: Displays the number of probes that passed and failed.
```

2023-01-24 08:07 UTC, SahilKr24 commented on src/Tooltip/TooltipDictionary.yaml
> +    content: Introduces randomness in pod deletions with a minimum period defined by CHAOS_INTERVAL environment variable.
Is `FAULT_RANDOMNESS` specific to Pod Delete?

2023-01-24 08:09 UTC, SahilKr24 commented on src/Tooltip/TooltipDictionary.yaml
> +    width: "400"
Older experiments might still have these in the fault CR, we can keep this, IMO

2023-01-24 08:10 UTC, SahilKr24 commented on src/Tooltip/TooltipDictionary.yaml
> +    width: "400"
Still have this in current and older manifests.

2023-01-24 08:13 UTC, neelanjan00 commented on src/Tooltip/TooltipDictionary.yaml
> +    width: "400"
We have removed lib everywhere now, ref: https://github.com/wings-software/enterprise-chaos-hub/pull/111

2023-01-24 08:14 UTC, neelanjan00 commented on src/Tooltip/TooltipDictionary.yaml
> +    width: "400"
We have removed this as well, ref: https://github.com/wings-software/enterprise-chaos-hub/pull/111

2023-01-24 08:19 UTC, SahilKr24 commented on src/Tooltip/TooltipDictionary.yaml
> +    width: "400"
I know, just that we can have this as a failsafe else we would need to add checks in frontend to not show tooltips for these if someone uploaded or edited an older manifest.

2023-01-24 08:32 UTC, SmritiSatya commented on src/Tooltip/TooltipDictionary.yaml
> +    content: Introduces randomness in pod deletions with a minimum period defined by CHAOS_INTERVAL environment variable.
Yes, I think so. I don't see that env var in any other fault. @SahilKr24

2023-01-24 08:39 UTC, SmritiSatya commented on src/Tooltip/TooltipDictionary.yaml
> +    content: Storage location of containers.
Location would mean file path, I think.

2023-01-24 08:42 UTC, SmritiSatya commented on src/Tooltip/TooltipDictionary.yaml
> +    content: Path to the socket file of the container runtime (for example, containerd, crio, or docker).
We aren't specifying DNS chaos anywhere, right? Also, it can be any container runtime, correct? That's why I have specified that as examples

2023-01-24 08:46 UTC, SmritiSatya commented on src/Tooltip/TooltipDictionary.yaml
> +    content: Map of the target host names ("abc.com":"spoofabc.com") where the key is the host name to be spoofed and the value is the host name to redirect to.
hostname and host name- both can be used.

2023-01-24 08:54 UTC, SmritiSatya commented on src/Tooltip/TooltipDictionary.yaml
> +    content: Number of I/O workers involved in I/O disk stress.
I think the terminology is I/O. I am changing in the faults too.

2023-01-24 08:57 UTC, SmritiSatya commented on src/Tooltip/TooltipDictionary.yaml
> +    content: Name of the probe used to perform chaos experiment health check.
This is added from UI, right? We are already inside the fault, and specify tunables and then move to 'Probes' tab where we specify name. Hence, I gave a specific description.

2023-01-24 09:35 UTC, deepakbolangady approved these changes
Approved. Changes look good.

2023-01-24 09:35 UTC, deepakbolangady commented on src/Tooltip/TooltipDictionary.yaml
> +    content: Number of I/O workers involved in I/O disk stress.
Agree with I/O. See https://www.google.com/search?client=firefox-b-d&q=input+output+abbreviation.

2023-01-24 09:50 UTC, merged

2023-01-24 09:53 UTC, neelanjan00 commented on src/Tooltip/TooltipDictionary.yaml
> +    content: Path to the socket file of the container runtime (for example, containerd, crio, or docker).
For DNS chaos we don't support crio and containerd, hence the modification.

2023-01-24 09:53 UTC, neelanjan00 commented on src/Tooltip/TooltipDictionary.yaml
> +    content: Number of I/O workers involved in I/O disk stress.
Then we should change it to I/O in line number 6503 too.

2023-01-24 09:53 UTC, neelanjan00 commented on src/Tooltip/TooltipDictionary.yaml
> +    content: Name of the probe used to perform chaos experiment health check.
Okay. But we should remove "experiment health check" since probes are scoped to faults.